#!/usr/bin/env python3
"""
Daily newsletter automation script
Run this via system cron at 6am: 0 6 * * * /usr/bin/python3 /path/to/daily_newsletter.py
"""
import sys
import os
sys.path.append(os.path.dirname(os.path.abspath(__file__)))

import feeds
from datamodel import Article, Group
from collections import defaultdict
from markdown import markdown
import smtplib
from email.message import EmailMessage
from datetime import datetime

def cluster_articles(articles):
    """Simple keyword-based clustering"""
    tags = [
        'Russia', 'Ukraine', 'NATO', 'Israel', 'Palestine', 'Hamas', 'Gaza',
        'China', 'Taiwan', 'Iran', 'Houthis', 'European Union',
        'United Kingdom', 'Germany', 'France', 'Japan', 'South Korea', 'Australia',
        'Canada', 'Mexico', 'Brazil', 'Argentina', 'Turkey', 'Saudi Arabia',
        'United States', 'Joe Biden', 'Trump', 'India',
        'Artificial Intelligence', 'Machine Learning', 'ChatGPT', 'OpenAI',
        'Technology', 'Science', 'Climate Change', 'Energy', 'Space',
        'Politics', 'Economy', 'Finance', 'Healthcare', 'Education'
    ]
    
    for i, article in enumerate(articles):
        article_text = f"{article.title} {article.summary}".lower()
        matched_keywords = []
        for tag in tags:
            if tag.lower() in article_text:
                matched_keywords.append(tag)
        article.keywords = matched_keywords[:5]
        
        if matched_keywords:
            cluster_hash = hash(frozenset(matched_keywords[:2]))
            article.cluster = abs(cluster_hash) % 10
        else:
            article.cluster = 0
    
    return articles

def generate_newsletter(articles):
    """Generate enhanced newsletter content"""
    clustered = cluster_articles(articles)
    
    newsletter_md = f"""# 📰 AIRSS Intelligence Brief - {datetime.now().strftime('%Y-%m-%d')}

*Your daily synthesis of global events and emerging trends*

---

## 🌍 Today's Key Developments

This intelligence brief synthesizes {len(articles)} articles from leading sources to identify emerging patterns and critical developments.

### Major Themes Identified:
"""

    # Group articles by cluster
    cluster_groups = defaultdict(list)
    for article in clustered:
        cluster_groups[article.cluster].append(article)

    for cluster_id, cluster_articles in cluster_groups.items():
        if len(cluster_articles) < 2:
            continue
            
        # Generate section title from keywords
        keys = defaultdict(int)
        for article in cluster_articles:
            for keyword in article.keywords:
                keys[keyword] += 1
        
        if keys:
            top_keywords = sorted(keys.items(), key=lambda x: x[1], reverse=True)
            section_title = ", ".join([keyword for keyword, count in top_keywords[:3]])
        else:
            section_title = f"Emerging Developments {cluster_id}"
        
        newsletter_md += f"\n\n## {section_title}\n\n"
        
        for article in cluster_articles[:5]:  # Top 5 articles per section
            newsletter_md += f"- **[{article.title}]({article.url})** - {article.source}\n"
            if article.summary:
                newsletter_md += f"  {article.summary[:150]}...\n"

    newsletter_md += f"""

---

## 📊 Intelligence Summary:
- **Articles Processed**: {len(articles)}
- **Themes Identified**: {len([g for g in cluster_groups.values() if len(g) >= 2])}
- **Sources**: NYT, Atlantic, MetaFilter, and others

---

*Generated by AIRSS at {datetime.now().strftime('%Y-%m-%d %H:%M')} • [Christopher Bonnell](mailto:christopherpbonnell+airss@gmail.com)*
"""

    return newsletter_md

def send_newsletter_email(newsletter_md):
    """Send newsletter with beautiful HTML formatting"""
    # Convert to HTML
    html_body = markdown(newsletter_md, extensions=['extra', 'codehilite'])
    
    html_content = f"""<!DOCTYPE html>
<html>
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>📰 AIRSS Intelligence Brief - {datetime.now().strftime('%Y-%m-%d')}</title>
    <style>
        body {{ 
            font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, sans-serif; 
            max-width: 800px; 
            margin: 0 auto; 
            padding: 20px;
            line-height: 1.6;
            color: #333;
        }}
        h1 {{ color: #2c3e50; border-bottom: 3px solid #3498db; padding-bottom: 10px; }}
        h2 {{ color: #34495e; border-bottom: 1px solid #bdc3c7; padding-bottom: 5px; margin-top: 30px; }}
        a {{ color: #3498db; text-decoration: none; }}
        a:hover {{ text-decoration: underline; }}
        strong {{ color: #2c3e50; }}
        em {{ color: #7f8c8d; }}
        hr {{ border: none; border-top: 2px solid #ecf0f1; margin: 30px 0; }}
        ul {{ margin: 15px 0; }}
        li {{ margin: 8px 0; }}
    </style>
</head>
<body>
    {html_body}
</body>
</html>"""

    # Send email
    sender = "christopherpbonnell@icloud.com"
    receiver = "christopherpbonnell+airss@gmail.com"
    password = "vqxh-oqrp-wjln-eagl"

    msg = EmailMessage()
    msg["From"] = sender
    msg["To"] = receiver
    msg["Subject"] = f"📰 AIRSS Intelligence Brief - {datetime.now().strftime('%Y-%m-%d')} (Auto)"
    msg.set_content(html_content, subtype="html")

    with smtplib.SMTP("smtp.mail.me.com", 587) as server:
        server.starttls()
        server.login(msg["From"], password)
        server.send_message(msg)

def main():
    """Main automation function"""
    try:
        print(f"[{datetime.now()}] Starting AIRSS daily newsletter generation...")
        
        # Fetch articles
        articles = feeds.Feeds.fetch_articles(feeds.FEEDS)
        print(f"Fetched {len(articles)} articles")
        
        # Generate newsletter
        newsletter = generate_newsletter(articles)
        print("Generated newsletter content")
        
        # Send email
        send_newsletter_email(newsletter)
        print("Newsletter sent successfully!")
        
    except Exception as e:
        print(f"Error: {e}")
        # Could add error notification here
        
if __name__ == "__main__":
    main()