#!/usr/bin/env python3
"""
Complete Newsletter Generator for AIRSS
Takes clustered articles and generates integrated narratives and complete newsletter using AI
"""

from datetime import datetime
from datamodel import Group, Article
from generate import generate


def generate_section_for_group(group_title, articles):
    """Generate a single newsletter section for a group of articles"""
    
    # Create rich content for the articles in this group
    articles_content = "\n".join([article.out_rich() for article in articles])
    
    section_prompt = f"""
I need to analyze this cluster of news articles probably relating to the following keywords "{group_title}" and create a compelling narrative section for a newsletter. Let me:

1. Identify the key themes and connections between the articles
2. Create a coherent story that weaves them together
3. Include proper source links
4. Skip if this is about sports, entertainment obituaries, music, or concerts
5. Focus on meaningful analysis and context

Transform this cluster of related news articles into a compelling newsletter section.

ARTICLES:
{articles_content}

OUTPUT FORMAT:
<h2>Compelling Section Title</h2>
<p>Narrative content with <a href="url">inline source links</a>. Explain connections between stories and provide meaningful context and analysis.</p>

Focus on creating a coherent, single-paragraph story from the clustered content rather than just summarizing individual articles."""

    try:
        section_content = generate(section_prompt)
        
        if not section_content or len(section_content.strip()) < 50:
            return None
            
        # Clean up content
        cleaned_content = section_content.strip()
        if cleaned_content.startswith('```html'):
            cleaned_content = cleaned_content[7:]
        if cleaned_content.endswith('```'):
            cleaned_content = cleaned_content[:-3]
        cleaned_content = cleaned_content.strip()
        
        # Skip if content is minimal or contains skip indicators
        if len(cleaned_content) < 50 or "skip" in cleaned_content.lower()[:100]:
            return None
            
        return cleaned_content
        
    except Exception as e:
        print(f"Error generating section for {group_title}: {e}")
        return None


def generate_newsletter_from_groups(groups_markdown):
    """Generate newsletter from clustered groups in markdown format - DEPRECATED"""
    # This is kept for backward compatibility but we should use the new method
    return generate_newsletter_from_group_objects(None)


def generate_newsletter_from_group_objects(groups):
    """Generate newsletter from Group objects by processing each group individually"""
    
    if not groups:
        print("No groups provided for newsletter generation")
        return generate_fallback_newsletter("No content available")
    
    print(f"Generating newsletter from {len(groups)} groups...")
    
    newsletter_sections = []
    
    # Process each group individually
    for group_id, group in groups.items():
        print(f"Processing group: {group.text}")
        
        section_content = generate_section_for_group(group.text, group.articles)
        
        if section_content:
            newsletter_sections.append(section_content)
            print(f"✓ Generated section for: {group.text}")
            print(section_content)
        else:
            print(f"✗ Skipped section for: {group.text}")
    
    if not newsletter_sections:
        print("No sections generated, creating fallback")
        return generate_fallback_newsletter("All sections were filtered out")
    
    # Combine all sections
    combined_content = "\n\n".join(newsletter_sections)
    
    # Wrap in complete HTML structure
    newsletter_html = f"""
<html>
<head>
    <meta charset="utf-8">
    <title>AI News Intelligence Brief</title>
    <style>
        body {{ font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, sans-serif; max-width: 800px; margin: 0 auto; padding: 20px; background-color: #fafafa; }}
        h1 {{ color: #1a73e8; border-bottom: 2px solid #1a73e8; padding-bottom: 15px; margin-bottom: 20px; }}
        h2 {{ color: #34a853; margin-top: 30px; margin-bottom: 15px; font-size: 20px; }}
        p {{ line-height: 1.6; margin-bottom: 15px; color: #333; }}
        a {{ color: #1a73e8; text-decoration: none; font-weight: 500; }}
        a:hover {{ text-decoration: underline; }}
    </style>
</head>
<body>
    <h1>📰 News Intelligence Brief - {datetime.now().strftime('%B %d, %Y')}</h1>
    <p style="color: #666; font-style: italic;">AI-generated narratives from clustered news stories</p>
    
    {combined_content}
    
    <hr style="margin: 40px 0 20px 0; border: none; border-top: 1px solid #dadce0;">
    <p style="color: #9aa0a6; font-size: 12px; text-align: center;">
        Generated by AIRSS Intelligence System • {datetime.now().strftime('%Y-%m-%d %H:%M UTC')}
    </p>
</body>
</html>
"""
    
    return newsletter_html


def generate_fallback_newsletter(reason):
    """Generate a fallback newsletter when main generation fails"""
    return f"""
<html>
<head>
    <meta charset="utf-8">
    <title>News Brief - {datetime.now().strftime('%Y-%m-%d')}</title>
</head>
<body style="font-family: Arial, sans-serif; max-width: 800px; margin: 0 auto; padding: 20px; background-color: #fafafa;">
    <h1 style="color: #1a73e8;">Today's News - {datetime.now().strftime('%B %d, %Y')}</h1>
    
    <p style="color: #666; font-style: italic;">Newsletter generation encountered an issue: {reason}</p>
    
    <hr style="margin: 30px 0; border: none; border-top: 1px solid #ddd;">
    <p style="color: #999; font-size: 12px; text-align: center;"><em>Generated by AIRSS</em></p>
</body>
</html>
"""